RonasIT/laravel-entity-generator

stubs/routes.blade.php
stubs/service.blade.php

#16:- feat: update templates;

---

ReadMe.md
config/entity-generator.php
src/Commands/MakeEntityCommand.php
src/Generators/ResourceGenerator.php
stubs/controller.blade.php
stubs/resource.blade.php

feat: generate resource class

---

config/entity-generator.php
src/Commands/MakeEntityCommand.php
src/Generators/FactoryGenerator.php
src/Generators/SeederGenerator.php
src/Generators/TestsGenerator.php
stubs/factory_separate_class.blade.php
stubs/model.blade.php
stubs/seeder_for_separate_factory.blade.php

feat: generate a separate factory

---

stubs/request.blade.php

https://github.com/RonasIT/laravel-entity-generator/issues/22#issuecomment-1460071364

#22: Update templates. Removed empty line generation from delete request

---

config/entity-generator.php
src/Commands/MakeEntityCommand.php
src/Generators/FactoryGenerator.php
src/Generators/SeederGenerator.php
stubs/database_seed_empty.blade.php
stubs/model.blade.php
stubs/request.blade.php

#20: Fixed bug with non-existent dir when creating new entity, renamed stub configs, added namespace for DatabaseSeeder

---

src/Generators/RequestsGenerator.php

@DenTray Done. Check it please

#33 Remove required rule for search request with required boolean field

---

ReadMe.md
src/Generators/TestsGenerator.php

fix: fix model mock for tests.

---

src/Commands/MakeEntityCommand.php
src/Generators/EntityGenerator.php

fix: modify model name to studly case by default.

---

src/Generators/ControllerGenerator.php
src/Generators/EntityGenerator.php
src/Generators/FactoryGenerator.php
src/Generators/MigrationGenerator.php
src/Generators/ModelGenerator.php
src/Generators/NovaResourceGenerator.php
src/Generators/RepositoryGenerator.php
src/Generators/RequestsGenerator.php
src/Generators/ResourceGenerator.php
src/Generators/SeederGenerator.php
src/Generators/ServiceGenerator.php
src/Generators/TestsGenerator.php
src/Generators/TranslationsGenerator.php
stubs/collection_resource.blade.php
stubs/controller.blade.php
stubs/database_empty_seeder.blade.php
stubs/factory.blade.php
stubs/legacy_empty_factory.blade.php
stubs/legacy_factory.blade.php
stubs/legacy_seeder.blade.php
stubs/model.blade.php
stubs/nova_resource.blade.php
stubs/repository.blade.php
stubs/request.blade.php
stubs/resource.blade.php
stubs/seeder.blade.php
stubs/service.blade.php
stubs/service_with_trait.blade.php
stubs/test.blade.php
stubs/use_routes.blade.php

feat: add classes namespace generation from path

---

src/Generators/NovaResourceGenerator.php

Correct logic for Nova resource creation

---

stubs/nova_test.blade.php
tests/fixtures/NovaTestGeneratorTest/created_resource_test.php

- fix generate data provider to test get filters data
- removed repeated request get admin from DB

Fix template for generarte nova tests

---

src/Generators/ResourceGenerator.php
stubs/resource.blade.php

refs: https://github.com/RonasIT/laravel-entity-generator/issues/103

feat: add property annotation

---

stubs/dumps/mysql.blade.php
stubs/dumps/pgsql.blade.php
tests/fixtures/NovaTestGeneratorTest/dump.sql

refs: https://github.com/RonasIT/laravel-entity-generator/issues/87

feat: Wrap table name into double quotes in dumps

---

src/Generators/RequestsGenerator.php

refs: https://github.com/RonasIT/laravel-entity-generator/issues/85

feat: Validate all search param as boolean instead of integer

---

stubs/resource.blade.php

refs: https://github.com/RonasIT/laravel-entity-generator/issues/103

fix: annotation

---

stubs/nova_test.blade.php
stubs/test.blade.php
tests/fixtures/NovaTestGeneratorTest/created_resource_test.php

feat: implemented supporting of PHPUnit v11

---

src/Generators/AbstractTestsGenerator.php
src/Generators/TestsGenerator.php
stubs/test.blade.php

refs: https://github.com/RonasIT/laravel-entity-generator/issues/97

Use model test states in tests generator

---

stubs/test.blade.php

refs: https://github.com/RonasIT/laravel-entity-generator/issues/97

fix: add model namespace

---

src/Generators/AbstractTestsGenerator.php
src/Generators/ControllerGenerator.php
stubs/controller.blade.php
stubs/migration.blade.php
stubs/model.blade.php
stubs/request.blade.php
stubs/routes.blade.php
stubs/service.blade.php
stubs/test.blade.php
tests/ControllerGeneratorTest.php
tests/fixtures/ControllerGeneratorTest/api.php
tests/fixtures/ControllerGeneratorTest/created_controller.php

refs: https://github.com/RonasIT/laravel-entity-generator/issues/112

112_update templates

---

src/EntityGeneratorServiceProvider.php

refs: https://github.com/RonasIT/laravel-entity-generator/issues/117

fix: config require

---

stubs/test.blade.php

refs: https://github.com/RonasIT/laravel-entity-generator/issues/97

feat: add assert for tests

---

src/Generators/AbstractTestsGenerator.php

https://github.com/RonasIT/laravel-entity-generator/issues/97

#97: Use model test states in tests generator

---

.gitattributes

refs: https://github.com/RonasIT/laravel-entity-generator/issues/135

feat: Create .gitattributes file

---

src/Enums/ResourceTypeEnum.php
src/Exceptions/ResourceAlreadyExistsException.php

refs: https://github.com/RonasIT/laravel-entity-generator/issues/178

[178]: add ResourceAlreadyExists exception

---

stubs/controller.blade.php

refs: https://github.com/RonasIT/laravel-entity-generator/issues/187

fix: correct controller.blade.php

---

src/Generators/EntityGenerator.php
src/Generators/ModelGenerator.php
src/Generators/NovaResourceGenerator.php
src/Generators/NovaTestGenerator.php
stubs/nova_resource.blade.php
tests/fixtures/CommandTest/subfolder/nova_resource.php

Refs: https://github.com/RonasIT/laravel-entity-generator/issues/64

fix: Correct NovaResource and NovaTest generation in subfolders

---

ReadMe.md

Updated installation and usage instructions in ReadMe.md to reflect changes in command usage and options.

Revise installation and usage sections in ReadMe.md

---

stubs/resource.blade.php
tests/fixtures/CommandTest/resource.php
tests/fixtures/CommandTest/subfolder/resource.php
tests/fixtures/ResourceGeneratorTest/post_resource.php

Refs: https://github.com/RonasIT/laravel-entity-generator/issues/198

refactor: update resource stub to extend BaseResource
